//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio.Mensagens {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mensagem {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensagem() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dominio.Mensagens.Mensagem", typeof(Mensagem).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data de entrada é superior a data de saída.
        /// </summary>
        public static string DataEntradaMenorQueDataSaida {
            get {
                return ResourceManager.GetString("DataEntradaMenorQueDataSaida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é permitida duplicidade de &quot;{0}&quot;.
        /// </summary>
        public static string EntidadeDuplicada {
            get {
                return ResourceManager.GetString("EntidadeDuplicada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é permitida duplicidade de &quot;{0}&quot; para o informado no campo &quot;{1}&quot;..
        /// </summary>
        public static string EntidadeDuplicadaPorEntidade {
            get {
                return ResourceManager.GetString("EntidadeDuplicadaPorEntidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O registro informado não foi encontrado..
        /// </summary>
        public static string EntidadeNaoEncontrada {
            get {
                return ResourceManager.GetString("EntidadeNaoEncontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo &quot;{0}&quot; não está válido.
        /// </summary>
        public static string ParametroInvalido {
            get {
                return ResourceManager.GetString("ParametroInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo &quot;{0}&quot; é obrigatório.
        /// </summary>
        public static string ParametroObrigatorio {
            get {
                return ResourceManager.GetString("ParametroObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo &quot;{0}&quot; deve ser único.
        /// </summary>
        public static string ParametroUnico {
            get {
                return ResourceManager.GetString("ParametroUnico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O registro &quot;{0}&quot; não foi encontrado.
        /// </summary>
        public static string RegistroNaoEncontrado {
            get {
                return ResourceManager.GetString("RegistroNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário ou senha inválidos.
        /// </summary>
        public static string UsuarioOuSenhaInvalido {
            get {
                return ResourceManager.GetString("UsuarioOuSenhaInvalido", resourceCulture);
            }
        }
    }
}
