//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio.Mensagens {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Termo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Termo() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dominio.Mensagens.Termo", typeof(Termo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celular.
        /// </summary>
        public static string Celular {
            get {
                return ResourceManager.GetString("Celular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente.
        /// </summary>
        public static string Cliente {
            get {
                return ResourceManager.GetString("Cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNPJ.
        /// </summary>
        public static string CNPJ {
            get {
                return ResourceManager.GetString("CNPJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF.
        /// </summary>
        public static string CPF {
            get {
                return ResourceManager.GetString("CPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        public static string Descricao {
            get {
                return ResourceManager.GetString("Descricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa.
        /// </summary>
        public static string Empresa {
            get {
                return ResourceManager.GetString("Empresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrou em.
        /// </summary>
        public static string EntrouEm {
            get {
                return ResourceManager.GetString("EntrouEm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forma de recebimento.
        /// </summary>
        public static string FormaRecebimento {
            get {
                return ResourceManager.GetString("FormaRecebimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movimentação.
        /// </summary>
        public static string Movimentacao {
            get {
                return ResourceManager.GetString("Movimentacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string Nome {
            get {
                return ResourceManager.GetString("Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil.
        /// </summary>
        public static string Perfil {
            get {
                return ResourceManager.GetString("Perfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placa.
        /// </summary>
        public static string Placa {
            get {
                return ResourceManager.GetString("Placa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recebimento.
        /// </summary>
        public static string Recebimento {
            get {
                return ResourceManager.GetString("Recebimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsável.
        /// </summary>
        public static string Responsavel {
            get {
                return ResourceManager.GetString("Responsavel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saiu em.
        /// </summary>
        public static string SaiuEm {
            get {
                return ResourceManager.GetString("SaiuEm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone.
        /// </summary>
        public static string Telefone {
            get {
                return ResourceManager.GetString("Telefone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário.
        /// </summary>
        public static string Usuario {
            get {
                return ResourceManager.GetString("Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor.
        /// </summary>
        public static string Valor {
            get {
                return ResourceManager.GetString("Valor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veículo.
        /// </summary>
        public static string Veiculo {
            get {
                return ResourceManager.GetString("Veiculo", resourceCulture);
            }
        }
    }
}
